### ISSUE TITLE
Issues Found in the Tex within the README

### ISSUE THREAD

**Issue by dslisleedh** [dah33/explore_forward_forward#1]
Firstly, I want to express my gratitude for the excellent summary on FF and the concept of utilizing the swish version of SymBa loss. I incorporated it into my [FF implementation](https://github.com/dslisleedh/FF-jax/blob/1692f7b9923dc842854784797bf7479b860357fc/src/losses.py#L47), and it yielded a significant performance boost. 👍 

However, I'm a bit puzzled about some parts of your README.md summary.

Initially, for the variable $y$ that denotes whether a sample is positive or negative, it should be represented as $-1$ when the sample is positive. The reasoning behind this is that $G_{pos}$ needs to be maximized, and softplus( $log(1 + e^x)$ ) gives a larger value(==loss) when the input is greater. Therefore, we must apply $-1$ to $G_{pos}$ in order to minimize $-G_{pos}$. The SymBa paper also mentions this in equation 2: $L_{pos} = log(1 + e^{\theta - G_{pos}})$.

Additionally, within the swish variant of the SymBa loss, the exponent $\alpha$ in the denominator should be $-\alpha$. 

Thanks for your time.

**Comment by dah33** [comment]
Thank you very much for proof reading my write up! I suspect you’re right. I’ll correct it 👍
