### ISSUE TITLE
Is the loss of original FF really the one stated in the paper ? 

### ISSUE THREAD

**Issue by lollopes** [dah33/explore_forward_forward#2]
Hi dah33, 

Very nice work with all these implementations. I was trying to go through the details of your implementation and discussion. I am slightly confused on the loss function of the original FF implementation. 

Your readme as well as the paper of Symba states that the original FF implements the following loss: 

L = log(p)

Where p = 1 + e^{\theta - G_{pos}}

However the original paper of Hinton states that p = logistic function, which should give the following: 

p = 1 / ( 1 + e^{\theta - G_{pos}})

Would you be able to clarify for me this difference ?

**Comment by dah33** [comment]
I think this is simply that Hinton wants to maximise the goodness, and in optimisation we usually want to minimise the loss, so this is a sign flip, which we achieve since `log(1/p) = -log(p)`.
